# Generated by Django 4.2.1 on 2023-05-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_contact_alter_comments_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttext',
            name='about_photo',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='generalpage',
            name='general_photo',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='port_img',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
